sudo: false

language: php

php: 7.0
#  - 5.3
#  - 5.4

before_script:
  - composer --dev --no-progress install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - php app/console cache:clear --env=test
  - php app/console assetic:dump --env=test

script: ./bin/phpunit -c ./app
