language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s https://getcomposer.org/installer | php -- --install-dir="symfony"
  - php ./symfony/composer.phar -v -o -d=symfony/ update

script: ./symfony/vendor/bin/phpunit -c ./symfony/app

