<?php

namespace VirtualPersistAPI\VirtualPersistBundle\Entity;

use Doctrine\ORM\EntityRepository;
use VirtualPersistAPI\VirtualPersistBundle\Entity\User;

/**
 * UserRepsitory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepsitory extends EntityRepository
{
    public function getAll()
    {
      try {
        $users = $this->_em
          ->createQuery('SELECT u FROM VirtualPersistBundle:User u')
          ->getResult();
        if (!empty($users)) {
          return $users;
        }
      } catch (\Exception $e) {
      }
      $user = new User();
      $user->setUuid('<none>');
      return array($user);
    }

    public function addUser(User $user) {
      $em = $this->_em;
      $conn = $em->getConnection();
      // Save the user inside a transaction.
      $conn->transactional(function($em, $user) {
        $em->persist($user);
        $em->flush();
      });
    }

    public function addUsers(array $users) {
      $em = $this->_em;
      $conn = $em->getConnection();
      // Transaction.
      $conn->transactional(function ($em, $users) {
        foreach($users as $user) {
          $this->addUser($user);
        }
      });
    }

}
