<?php

namespace VirtualPersistAPI\VirtualPersistBundle\Entity;

use Doctrine\ORM\EntityRepository;
use VirtualPersistAPI\VirtualPersistBundle\Entity\User;

/**
 * UserRepsitory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepsitory extends EntityRepository
{
    public function getAll()
    {
      try {
        $users = $this->_em
          ->createQuery('SELECT u FROM VirtualPersistBundle:User u')
          ->getResult();
        if (!empty($users)) {
          return $users;
        }
      } catch (\Exception $e) {
      }
      $user = new User();
      $user->setUuid('<none>');
      return array($user);
    }
}
