<?php

namespace VirtualPersistAPI\VirtualPersistBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * RecordRepsitory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository {

  public function getNewest($count) {
    $query = $this->getEntityManager()
      ->createQuery('
        SELECT l FROM VirtualPersistBundle:Log l
        ORDER BY l.timestamp DESC'
      )
      ->setMaxResults($count);
    $result = $query->getResult();
    return $result;
  }

}
